### ISSUE TITLE
tidy `napari` classifiers

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/BrainGlobe#57]
* remove from `brainreg-segment` and `brainreg-napari`
* add to `brainreg`

**Comment by willGraham01** [comment]
- [ ] Remove from `brainreg-segment`
- [ ] Remove from `brainreg-napari`
- [ ] https://github.com/brainglobe/brainreg/issues/167 (Add to `brainreg`)

**Comment by willGraham01** [comment]
`brainreg-segment` is going to be tricky to remove since we're recycled the repository name.

I think the best way to do this is for someone (me) to check out [04bc1a29c19a51e6d6679904644e07077b9bd68f](https://github.com/brainglobe/brainglobe-segmentation/tree/04bc1a29c19a51e6d6679904644e07077b9bd68f) locally, then create a new branch off here to update the OLD `brainreg-segment` package, and push this to PyPI manually. 

This branch can then also be pushed to the remote (and marked as old/retired/stale) in the event that we need to perform further updates to the old-named package.

**Comment by willGraham01** [comment]
[`brainreg-napari`](https://github.com/brainglobe/brainreg-napari) will have to be un-archived, updated, then re-archived to achieve this.
